version: '3.9'

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb-free
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: unionlogin
      MYSQL_USER: appuser
      MYSQL_PASSWORD: app123
    volumes:
      - mariadb-data:/var/lib/mysql

volumes:
  mariadb-data: